apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-log-pull
  labels:
    app: runtime-log-pull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime-log-pull
  template:
    metadata:
      labels:
        app: runtime-log-pull
    spec:
      containers:
      - name: runtime-log-pull
        image: gcr.io/mechmania2017/runtime-log-pull:latest
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: creds
                key: mongo
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_secret_access_key
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /gcr
          name: gcr
          readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: gcr
        secret:
          secretName: gcr
---
apiVersion: v1
kind: Service
metadata:
  name: runtime-log-pull-service
spec:
  type: LoadBalancer
  selector:
    app: runtime-log-pull
  ports:
  - port: 80
    name: runtime-log-pull-service
    targetPort: 3000
    protocol: TCP