apiVersion: apps/v1
kind: Deployment
metadata:
  name: mm-runtime-log-pull
  labels:
    app: mm-runtime-log-pull
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mm-runtime-log-pull
  template:
    metadata:
      labels:
        app: mm-runtime-log-pull
    spec:
      containers:
      - name: mm-runtime-log-pull
        image: gcr.io/mechmania2017/mm-runtime-log-pull:latest
        env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: creds
                key: mongo
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: creds
                key: aws_secret_access_key
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
        - mountPath: /gcr
          name: gcr
          readOnly: true
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: gcr
        secret:
          secretName: gcr
